; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri Jan 17 2020 10:35:55 GMT-0600 (Central Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


